import { TeamMember, Project, Task } from "@/types";

export const MONTHLY_CAPACITY_LIMIT = 200;
export const STANDARD_HOURS_PER_DAY = 10;
export const TOTAL_HOURS_IN_DAY = 12;

// ─── TEAM DATA ───────────────────────────────────────────────────────────────
export const INITIAL_TEAM_DATA: TeamMember[] = [
  {
    id: "emp1",
    name: "Amr Sabry",
    role: "Creative Director",
    email: "amr@aromastudios.com",
    status: "online",
    skills: ["Art Direction", "Concept Development", "Leadership"],
    software: ["Photoshop", "Illustrator", "Figma"],
    capacityHours: MONTHLY_CAPACITY_LIMIT,
    bookedHours: 0,
    availableHours: MONTHLY_CAPACITY_LIMIT,
    metrics: { speed: 9, quality: 10, creativity: 9.5, reliability: 9, teamwork: 8.5 },
    activeTaskId: null,
    nextFreeSlot: "18:00",
  },
  {
    id: "emp2",
    name: "Mohamed Safwat",
    role: "Creative Designer",
    email: "safwat@aromastudios.com",
    status: "busy",
    skills: ["3D Modeling", "Texturing", "Lighting"],
    software: ["3ds Max", "V-Ray", "ZBrush"],
    capacityHours: MONTHLY_CAPACITY_LIMIT,
    bookedHours: 0,
    availableHours: MONTHLY_CAPACITY_LIMIT,
    metrics: { speed: 8, quality: 9.5, creativity: 9, reliability: 9.5, teamwork: 9 },
    activeTaskId: null,
    nextFreeSlot: "18:00",
  },
  {
    id: "emp3",
    name: "Mohamed Abbas",
    role: "Creative Designer",
    email: "abbas@aromastudios.com",
    status: "online",
    skills: ["Stage Design", "Visualizing", "Layout"],
    software: ["AutoCAD", "SketchUp", "Revit"],
    capacityHours: MONTHLY_CAPACITY_LIMIT,
    bookedHours: 0,
    availableHours: MONTHLY_CAPACITY_LIMIT,
    metrics: { speed: 9.5, quality: 8, creativity: 8.5, reliability: 9, teamwork: 9 },
    activeTaskId: null,
    nextFreeSlot: "15:00",
  },
  {
    id: "emp4",
    name: "Rana Elsherbeny",
    role: "Creative Designer",
    email: "rana@aromastudios.com",
    status: "busy",
    skills: ["Graphic Design", "Branding", "Typography"],
    software: ["Figma", "Illustrator", "Photoshop"],
    capacityHours: MONTHLY_CAPACITY_LIMIT,
    bookedHours: 0,
    availableHours: MONTHLY_CAPACITY_LIMIT,
    metrics: { speed: 9, quality: 9, creativity: 9.5, reliability: 8, teamwork: 9 },
    activeTaskId: null,
    nextFreeSlot: "Tomorrow",
  },
  {
    id: "emp5",
    name: "Fatma Elawady",
    role: "Creative Designer",
    email: "fatma@aromastudios.com",
    status: "busy",
    skills: ["UI/UX Design", "Wireframing", "Prototyping"],
    software: ["Figma", "Adobe XD", "Sketch"],
    capacityHours: MONTHLY_CAPACITY_LIMIT,
    bookedHours: 0,
    availableHours: MONTHLY_CAPACITY_LIMIT,
    metrics: { speed: 8.5, quality: 9, creativity: 8.5, reliability: 9.5, teamwork: 9 },
    activeTaskId: null,
    nextFreeSlot: "14:30",
  },
  {
    id: "emp6",
    name: "Ahmed Esmail",
    role: "Creative Designer",
    email: "ahmed@aromastudios.com",
    status: "online",
    skills: ["Motion Graphics", "VFX", "Compositing"],
    software: ["After Effects", "Cinema 4D", "Blender"],
    capacityHours: MONTHLY_CAPACITY_LIMIT,
    bookedHours: 0,
    availableHours: MONTHLY_CAPACITY_LIMIT,
    metrics: { speed: 8, quality: 8.5, creativity: 8, reliability: 9, teamwork: 8.5 },
    activeTaskId: null,
    nextFreeSlot: "17:00",
  },
];

// ─── PROJECTS DATA ──────────────────────────────────────────────────────────
export const INITIAL_PROJECTS_DATA: Project[] = [
  {
    id: "p1",
    name: "Ora Iraq AI AD",
    client: "Ora Developers",
    budgetHours: 250,
    deadline: "2025-11-25",
    status: "Active",
    health: "Good",
    milestones: [
      { title: "PPM", date: 10, completed: true },
      { title: "Anim Lock", date: 20, completed: false },
    ],
  },
  {
    id: "p2",
    name: "Police Event",
    client: "Police Brand",
    budgetHours: 120,
    deadline: "2025-11-22",
    status: "Critical",
    health: "Risk",
    milestones: [{ title: "Stage Setup", date: 18, completed: true }],
  },
  {
    id: "p3",
    name: "Saudi Musical Designs",
    client: "Riyadh Season",
    budgetHours: 300,
    deadline: "2025-11-30",
    status: "Active",
    health: "Good",
    milestones: [{ title: "Theme 1", date: 25, completed: false }],
  },
  {
    id: "p4",
    name: "Kaya Real Estate",
    client: "Kaya",
    budgetHours: 80,
    deadline: "2025-11-28",
    status: "Active",
    health: "Good",
    milestones: [],
  },
  {
    id: "p5",
    name: "Ward 3ala Fol w Yasmin",
    client: "TV Series",
    budgetHours: 100,
    deadline: "2025-12-01",
    status: "Active",
    health: "Good",
    milestones: [],
  },
];

// ─── TASKS DATA ─────────────────────────────────────────────────────────────
export const INITIAL_TASKS_DATA: Task[] = [
  {
    id: "t1",
    title: "AI Scene Gen (Seq 3-4)",
    project: "Ora Iraq AI AD",
    type: "AI Gen",
    assignees: ["Amr Sabry"],
    producer: "Maryam Elzeiny",
    status: "In Progress",
    workState: "play",
    estHours: 8,
    actualHours: 4.5,
    startTime: new Date("2025-11-18T14:00:00").toISOString(),
    deadline: "2025-11-20",
    deadlineTime: "17:00",
    startDay: 18,
    duration: 3,
    risk: "low",
    note: "Focus on cinematic lighting for sequence 4.",
    deliverables: [
      { type: "MP4", count: 3, specs: "4K" },
      { type: "JPG", count: 10, specs: "Preview Quality" },
    ],
    requiredSkills: ["Art Direction"],
    requiredSoftware: ["Photoshop"],
    extensions: [],
    weekendHandling: "exclude_both",
    dailyStartTime: "09:00",
    dailyEndTime: "17:00",
  },
  {
    id: "t3",
    title: "Main Stage 3D Theme",
    project: "Police Event",
    type: "3D",
    assignees: ["Mohamed Safwat", "Amr Sabry"],
    producer: "Farida",
    status: "In Progress",
    workState: "play",
    estHours: 13,
    actualHours: 10.5,
    startTime: new Date("2025-11-19T10:00:00").toISOString(),
    deadline: "2025-11-21",
    deadlineTime: "18:00",
    startDay: 19,
    duration: 4,
    risk: "high",
    note: "Critical deadline. Rework due to complex client requirements.",
    deliverables: [{ type: "PSD", count: 1, specs: "Open Layers" }],
    requiredSkills: ["3D Modeling", "Texturing"],
    requiredSoftware: ["3ds Max", "V-Ray"],
    extensions: [],
    weekendHandling: "exclude_both",
    dailyStartTime: "09:00",
    dailyEndTime: "17:00",
  },
  {
    id: "t4",
    title: "Event Hall Layouts",
    project: "Police Event",
    type: "Design",
    assignees: ["Mohamed Abbas"],
    producer: "Farida",
    status: "In Progress",
    workState: "meeting",
    estHours: 6,
    actualHours: 1,
    startTime: new Date("2025-11-19T09:30:00").toISOString(),
    deadline: "2025-11-20",
    deadlineTime: "15:30",
    startDay: 19,
    duration: 2,
    risk: "low",
    note: "Initial concept meeting is ongoing.",
    deliverables: [{ type: "PDF", count: 1, specs: "A3 Print Ready" }],
    requiredSkills: ["Stage Design", "Layout"],
    requiredSoftware: ["AutoCAD"],
    extensions: [],
    weekendHandling: "exclude_both",
    dailyStartTime: "09:00",
    dailyEndTime: "17:00",
  },
  {
    id: "t5",
    title: "Riyadh Concert Theme A",
    project: "Saudi Musical Designs",
    type: "Design",
    assignees: ["Rana Elsherbeny"],
    producer: "Yasmin",
    status: "In Progress",
    workState: "play",
    estHours: 16,
    actualHours: 14.5,
    startTime: new Date("2025-11-15T09:00:00").toISOString(),
    deadline: "2025-11-25",
    deadlineTime: "17:00",
    startDay: 15,
    duration: 10,
    risk: "medium",
    note: "Rana on vacation starting 26/11. Finalizing visuals.",
    deliverables: [{ type: "AI", count: 5, specs: "Vector Source" }],
    requiredSkills: ["Graphic Design", "Branding"],
    requiredSoftware: ["Illustrator"],
    extensions: [],
    weekendHandling: "include_both",
    dailyStartTime: "09:00",
    dailyEndTime: "17:00",
  },
  {
    id: "t6",
    title: "Concert Screens Anim",
    project: "Saudi Musical Designs",
    type: "Animation",
    assignees: ["Ahmed Esmail"],
    producer: "Yasmin",
    status: "To Do",
    workState: "pause",
    estHours: 12,
    actualHours: 0,
    startTime: new Date("2025-11-22T10:00:00").toISOString(),
    deadline: "2025-11-26",
    deadlineTime: "18:00",
    startDay: 22,
    duration: 5,
    risk: "low",
    note: "Waiting for Theme A final sign-off.",
    deliverables: [{ type: "MOV", count: 8, specs: "Alpha Channel" }],
    requiredSkills: ["Motion Graphics"],
    requiredSoftware: ["After Effects", "Cinema 4D", "Blender"],
    extensions: [],
    weekendHandling: "exclude_both",
    dailyStartTime: "09:00",
    dailyEndTime: "17:00",
  },
  {
    id: "t8",
    title: "Title Seq Typography",
    project: "Ward 3ala Fol w Yasmin",
    type: "Design",
    assignees: ["Fatma Elawady"],
    producer: "Malak",
    status: "To Do",
    workState: "pause",
    estHours: 8,
    actualHours: 0,
    startTime: new Date("2025-11-25T09:30:00").toISOString(),
    deadline: "2025-11-29",
    deadlineTime: "16:00",
    startDay: 25,
    duration: 4,
    risk: "low",
    note: "Upcoming task, waiting for episode scripts.",
    deliverables: [{ type: "PNG", count: 15, specs: "Transparent BG" }],
    requiredSkills: ["UI/UX Design"],
    requiredSoftware: ["Figma"],
    extensions: [],
    weekendHandling: "exclude_both",
    dailyStartTime: "09:00",
    dailyEndTime: "17:00",
  },
];

// ─── GLOBAL CONFIG ───────────────────────────────────────────────────────────
export const GLOBAL_SKILLS = [
  "Art Direction",
  "Concept Development",
  "3D Modeling",
  "Texturing",
  "Stage Design",
  "Visualizing",
  "Layout",
  "Graphic Design",
  "Branding",
  "UI/UX Design",
  "Wireframing",
  "Motion Graphics",
  "VFX",
  "Leadership",
  "Lighting",
  "ZBrush",
  "Revit",
  "Typography",
  "Prototyping",
  "Sketch",
  "Compositing",
  "Blender",
].sort();

export const GLOBAL_SOFTWARE = [
  "Photoshop",
  "Illustrator",
  "Figma",
  "3ds Max",
  "V-Ray",
  "ZBrush",
  "AutoCAD",
  "SketchUp",
  "Revit",
  "Adobe XD",
  "Sketch",
  "After Effects",
  "Cinema 4D",
  "Blender",
].sort();

export const GLOBAL_DELIVERABLES = [
  { type: "MP4", specs: ["4K", "1080p", "H.264"] },
  { type: "PSD", specs: ["Open Layers", "Flat"] },
  { type: "AI", specs: ["Vector Source", "Outlined Fonts"] },
  { type: "PDF", specs: ["A3 Print Ready", "Presentation", "Web Optimized"] },
  { type: "JPG", specs: ["Preview Quality", "High Res", "Web Optimized"] },
  { type: "PNG", specs: ["Transparent BG", "High Res"] },
  { type: "MOV", specs: ["Alpha Channel", "H.264", "ProRes"] },
];

export const PRODUCERS = [
  "Maryam Elzeiny",
  "Farida",
  "Yasmin",
  "Malak",
];
